# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /usr/src/app

# Copy project files into the container
COPY package*.json ./
COPY index.js ./
COPY README.md ./
COPY LICENSE ./

# Install dependencies
RUN npm install --production --ignore-scripts

# Expose any ports if needed (not necessary for stdio MCP server)

# Start the MCP server
CMD ["node", "index.js"]
